version: '2.2'

services:
  samba:
    image: "mmtnrw/samba-sorted:latest"
    restart: always
    network_mode: host
    privileged: true
    tty: true
    volumes:
      - "./backup:/backup"
      - "./scan:/scan"
    environment:
       TZ: "Europe/Amsterdam"
       LISTEN: "127.0.0.1"
